### ISSUE TITLE
Teach is broken

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#34]
D 20171025-1835:50,441 requests.packages.urllib3.connectionpool http://localhost:4567 "POST /teach HTTP/1.1" 301 263 [dispatcher]
D 20171025-1835:50,447 requests.packages.urllib3.connectionpool Resetting dropped connection: localhost [dispatcher]
D 20171025-1835:50,449 requests.packages.urllib3.connectionpool http://localhost:4567 "GET /teach/ HTTP/1.1" 405 64 [dispatcher]
I 20171025-1835:50,449 common.request Received response: {'message': 'The method is not allowed for the requested URL.'} [dispatcher]
E 20171025-1835:50,449 telegram.ext.dispatcher An uncaught error was raised while processing the update [dispatcher]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/mrt/UT/tp/waldurchatbot/TelegramBot/telegrambot/telegrambot.py", line 34, in query
    response = conn.get_response(message, user_id)
  File "/usr/local/lib/python3.5/dist-packages/common/request.py", line 40, in get_response
    response = self._handle_message(user_id, message)
  File "/usr/local/lib/python3.5/dist-packages/common/request.py", line 59, in _handle_message
    self.teach(self.last_bot_response, self.last_query)
  File "/usr/local/lib/python3.5/dist-packages/common/request.py", line 129, in teach
    raise Exception(response['message'])
Exception: The method is not allowed for the requested URL

**Comment by m2rtk** [comment]
Teach is removed as of fa357a4dc022f232f882ea5587f5b2d2c4b28298
Created a new issue #56
